### ISSUE TITLE
Katherine cannot take Reducto?

### ISSUE THREAD

**Issue by BrighteyesOK** [herp-a-derp/CoC-Alpha#8]
Whenever I try to give Kath some Reducto, all the text disappears from the main window.  I can still make selections on the bottom, though.   However, none of the options change when I select to give her Reducto.

**Comment by dragontamer8740** [comment]
This is the wrong place to report this. You want to report this issue in https://github.com/herp-a-derp/Corruption-of-Champions/issues .
I'm not anyone with power in this project, I just want to point that out though.
The only issues in this repository should be related to the packaging process of the game.
